steps:
  # Build image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/getpolvo:$SHORT_SHA', '.' ]
  # Push image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/getpolvo:$SHORT_SHA']
  # init
  - name: 'hashicorp/terraform:1.0.5'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      cd infrastructure/terraform
      terraform init -var="docker_image_url=gcr.io/$PROJECT_ID/getpolvo:$SHORT_SHA" -reconfigure -backend-config="bucket=$PROJECT_ID-tfstate"

  # plan
  - name: 'hashicorp/terraform:1.0.5'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
      cd infrastructure/terraform
      terraform plan -var="docker_image_url=gcr.io/$PROJECT_ID/getpolvo:$SHORT_SHA" -reconfigure -backend-config="bucket=$PROJECT_ID-tfstate"
