steps:
  # Build image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/getpolvo@$BRANCH_NAME', '.' ]
  # init
#  - name: 'hashicorp/terraform:1.0.5'
#    entrypoint: 'sh'
#    args:
#    - '-c'
#    - |
#      cd infrastructure/terraform
#      terraform init

  # plan
#  - name: 'hashicorp/terraform:1.0.5'
#    entrypoint: 'sh'
#    args:
#    - '-c'
#    - |
#      cd infrastructure/terraform
#      terraform plan
